version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: genz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/genz
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=*
      - JWT_SECRET_KEY=dev
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  web:
    build:
      context: .
    dockerfile: apps/web/Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    depends_on:
      - api
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  pgdata: 