image:
  repository: ghcr.io/OWNER/genz-web
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: [] # e.g., [{ name: regcred }]

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

env:
  NEXT_PUBLIC_API_BASE_URL: "http://genz-api:8000"

secretRef: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
