replicaCount: 3
image:
  tag: latest
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65
pdb:
  enabled: true
  minAvailable: 1
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts: [app.example.com]
      secretName: app-tls
secretRef: "" # use existing secret in cluster
