image:
  repository: ghcr.io/intellwe/genz-web
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: [{ name: regcred }]

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

env:
  NEXT_PUBLIC_API_BASE_URL: "http://genz-api:8000"

secret:
  create: false
  name: genz-web-env
  data: {}

secretRef: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: false
  minAvailable: 1
