image:
  repository: ghcr.io/intellwe/genz-api
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: [{ name: regcred }]

replicaCount: 2

service:
  type: ClusterIP
  port: 8000

env:
  DATABASE_URL: "postgresql+psycopg://postgres:postgres@postgres:5432/genz"
  REDIS_URL: "redis://redis:6379/0"
  CORS_ORIGINS: "*"
  JWT_SECRET_KEY: "change-me"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"

secret:
  create: false
  name: genz-api-env
  data: {}

secretRef: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: false
  minAvailable: 1

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
  annotations: {}
