image:
  repository: ghcr.io/OWNER/genz-api
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: [] # e.g., [{ name: regcred }]

replicaCount: 2

service:
  type: ClusterIP
  port: 8000

env:
  DATABASE_URL: "postgresql+psycopg://postgres:postgres@postgres:5432/genz"
  REDIS_URL: "redis://redis:6379/0"
  CORS_ORIGINS: "*"
  JWT_SECRET_KEY: "change-me"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"

secretRef: "" # set to mount a secret with extra envs

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
