import { useState } from "react";
import "./popup.css";

export default function Popup() {
  const [model, setModel] = useState("openai:gpt-4o-mini");
  const [tone, setTone] = useState("concise");
  const [includeContext, setIncludeContext] = useState(true);

  return (
    <div className="popup">
      <h1>Genz</h1>
      <label>
        Model
        <select value={model} onChange={(e) => setModel(e.target.value)}>
          <option value="openai:gpt-4o-mini">OpenAI · gpt-4o-mini</option>
          <option value="anthropic:claude-3-haiku">
            Anthropic · Claude 3 Haiku
          </option>
          <option value="gemini:1.5-flash">Gemini · 1.5 Flash</option>
        </select>
      </label>
      <label>
        Tone
        <select value={tone} onChange={(e) => setTone(e.target.value)}>
          <option value="concise">Concise</option>
          <option value="professional">Professional</option>
          <option value="friendly">Friendly</option>
          <option value="assertive">Assertive</option>
        </select>
      </label>
      <label className="row">
        <input
          type="checkbox"
          checked={includeContext}
          onChange={(e) => setIncludeContext(e.target.checked)}
        />
        <span>Include page context</span>
      </label>
      <button onClick={() => window.close()}>Close</button>
      <footer>Generated by Genz</footer>
    </div>
  );
}

// Mount
import { createRoot } from "react-dom/client";
const root = createRoot(document.getElementById("root")!);
root.render(<Popup />);
