name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: env.GHCR_PAT != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GHCR_PAT }}

      - name: Log in to Docker Hub
        if: env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != ''
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: vars
        run: |
          SHA_TAG=${GITHUB_SHA::7}
          if [[ "${GITHUB_REF##*/}" == "main" || "${GITHUB_REF##*/}" == "master" ]]; then BRANCH_TAG=latest; else BRANCH_TAG=${GITHUB_REF##*/}; fi
          echo "sha_tag=$SHA_TAG" >> $GITHUB_OUTPUT
          echo "branch_tag=$BRANCH_TAG" >> $GITHUB_OUTPUT

      - name: Build and push API image to GHCR
        if: env.GHCR_PAT != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/genz-api:${{ steps.vars.outputs.sha_tag }}
            ghcr.io/${{ github.repository_owner }}/genz-api:${{ steps.vars.outputs.branch_tag }}

      - name: Build and push Web image to GHCR
        if: env.GHCR_PAT != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/genz-web:${{ steps.vars.outputs.sha_tag }}
            ghcr.io/${{ github.repository_owner }}/genz-web:${{ steps.vars.outputs.branch_tag }}

      - name: Build and push API image to Docker Hub
        if: env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/genz-api:${{ steps.vars.outputs.sha_tag }}
            ${{ env.DOCKERHUB_USERNAME }}/genz-api:${{ steps.vars.outputs.branch_tag }}

      - name: Build and push Web image to Docker Hub
        if: env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/genz-web:${{ steps.vars.outputs.sha_tag }}
            ${{ env.DOCKERHUB_USERNAME }}/genz-web:${{ steps.vars.outputs.branch_tag }}
